# -*- coding: utf-8 -*-
"""object detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRdsEyCvF-JRvvhJFPel2d03e7hggB6K
"""

!nvidia-smi

!uv pip install ultralytics
import ultralytics
ultralytics.checks()

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Q4mrgmrZ61DoLmhTZqh4")
project = rf.workspace("nightbot-4abzw").project("waste-super-6rckc")
version = project.version(1)
dataset = version.download("yolov11")

from ultralytics import YOLO

# 1. Load the model
model = YOLO("yolo11n.pt")

# 2. Train using the downloaded dataset
results = model.train(
    data="/content/Waste-Super-1/data.yaml",  # <--- This points to your new data
    epochs=50,
    imgsz=640
)